services:
  - type: web
    name: military-asset-management-api
    env: node
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: military-assets-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPLIT_DOMAINS
        sync: false
      - key: REPL_ID
        sync: false

databases:
  - name: military-assets-db
    databaseName: military_assets
    user: admin
    plan: free